# Generated by Django 4.2.23 on 2025-08-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('brand', models.CharField(help_text='Виробник/бренд', max_length=120, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, help_text='Короткий опис товару', verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, help_text='UAH', max_digits=10, verbose_name='Ціна')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='Знижка, %')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='На складі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('warranty_months', models.PositiveIntegerField(default=12, help_text='К-ть місяців гарантії', verbose_name='Гарантія, міс')),
                ('energy_class', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=4, verbose_name='Клас енергоефективності')),
                ('color', models.CharField(choices=[('white', 'Білий'), ('black', 'Чорний'), ('silver', 'Сріблястий'), ('gray', 'Сірий'), ('red', 'Червоний')], default='white', max_length=12, verbose_name='Колір')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
    ]
